language: go
go:
- 1.10.3
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: UeBIvjn9NeBEK4Gbsrx30TWurvAWigptGc41y4umOpeELd/jhl2EFZD8gvex1SyAi1KJUL01t31uCB5r9vhY3DvSNBIjkMU/CotUMqiy1hbqk6hjFC8XOAYzSbBT5Fzm1WvGrkgefpASiGwD3PtNhbNVr8TeFOGumdHajXYSOG0QYB/pWZ5l2UX+2d28/4/wK39TgO4AsL9fgFM7dAKqN3obszJK4lU3/N6x8NLdBhctU3/kzxawuDY8D5B+uSPr0kkOzBGdwJ0p1sTRROjcu+AO2GKsdLldjWt3aj1uhvB7O5EmwxbmJkWrPC1IEUKxEQzrMAkvlKHMUq8ZX455+PTarg4miPoPI1O2Ih7IcdEMSP8E9K91DNOsr2v4fzqt4waYHvOa7I6XJ9XwCl6Zf5UDmS7qYs3N2JmYQerRFGv4nRak7iK57gheYhwUNBFAmyc2zq7JjatxESjKhuc48JuG4razWVL4+veLM+uHr3Xss9OSnV0S+Jvbz4e2Flz08TQlTWUBLppezKOTecMJ21chcaxykG2+zrnWWHIHSBXW76Bc5KNPzCfGPnarzNSkbdWvZhiuaIsNKrCCJA7yIlKkoEDnUuDHbQM2NYxk9JXP+SXtLTcheKShxNdrL5ABonhGumaxdABRnBjVttMEX4i6BlvfyAJsasx8D1ANb5o=
  app: accounts-go
  on:
    repo: wederch/accounts-go
